### ISSUE TITLE
Newest twitch update breaks login again

### ISSUE THREAD

**Issue by AMlG0** [level3tjg/TwitchLoginFix#1]
Hello,

Yesterday (March 20th, 2023) twitch pushed an update and it seems to cause the “you must be on the latest firmware” prompt to come up again. I can login on the app on anything running iOS 15 and up. I have tried it on iPad running u0 13.5 and iPhone 12 pro running u0 14.1. It’s weird because it still says minimum iOS version required is 13.0 in the plist. 

I ran into this issue before but installing this tweak solved it, albeit for the the time being. Now it seems to have broken again. I can’t find anything on Reddit or in any of the discord’s about this, so I was wondering if it was possible for you to take a look at and see if it’s something you could fix? 

Thanks in advance for your time!

**Comment by level3tjg** [comment]
Login issues should be fixed by e9959b1

**Comment by AMlG0** [comment]
Awesome you’re a legend, thank you! It works again now.
